[package]
name = "zmigrate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
hex = "0.4.3"
owo-colors = "4.1.0"
sha2 = "^0.10.6"
clap = { version = "^4.4.3", features = ["derive", "unstable-styles"] }
anstyle = "^1.0.1"
sapling-crypto = "0.5.0"
zcash_primitives = "0.22.0"
zcash_client_backend = "0.17.0"
prost = { version = "0.13.5", features = ["prost-derive"] }

[features]
default = []
with-context = []
