[package]
name = "zmigrate"
version = "0.1.0"
edition = "2024"

[dependencies]
zewif = { path = "../zewif" }
zewif-zcashd = { path = "../zewif-zcashd" }
zewif-zingo = { path = "../zewif-zingo" }

anyhow = "1.0.95"
chrono = "0.4.39"
hex = "0.4.3"
owo-colors = "4.1.0"
sha2 = "^0.10.6"
clap = { version = "^4.4.3", features = ["derive", "unstable-styles"] }
anstyle = "^1.0.1"
bc-components = "^0.17.0"
bc-envelope = "^0.24.0"
sapling-crypto = "0.3"
ripemd = "0.1.3"
zcash_address = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.12.1_plus_zingolabs_changes-test_2" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.12.1_plus_zingolabs_changes-test_2" }
zcash_client_backend = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.12.1_plus_zingolabs_changes-test_2", features = [
    "lightwalletd-tonic",
    "orchard",
    "transparent-inputs",
] }
zcash_keys = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.12.1_plus_zingolabs_changes-test_2", features = [
    "transparent-inputs",
    "sapling",
    "orchard",
] }
zcash_encoding = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.12.1_plus_zingolabs_changes-test_2" }
prost = { version = "0.13.5", features = ["prost-derive"] }
orchard = "0.11.0"
incrementalmerkletree = "0.8.2"
zcash_protocol = "0.5.0"
zingolib = { git = "https://github.com/zingolabs/zingolib.git", rev = "965e81228d3a1d99b76c1e3c71202d8fdbbd41dc", features = [
    "test-elevation",
] }
append-only-vec = { git = "https://github.com/zancas/append-only-vec.git", branch = "add_debug_impl" }
byteorder = "1.5.0"
bip0039 = "=0.11.0"
jubjub = "0.10"
group = "0.13"

[features]
default = []
with-context = []
